### ISSUE TITLE
epic(roadmap): re-alignment roadmap — gates first, then core and AI tracks

### ISSUE THREAD

**Issue by TurboCoder13** [lgtm-hq/py-lintro#2288]
## Summary

This is the execution plan an agent works through unattended. It links every re-alignment issue, fixes the order, states what "done" means mechanically at each step, and says what each step must not touch. It restates nothing: the task spec for every step is its own issue.

Origin: the 2026-09-03 engineering audit. Verdict: hygiene gates are green (mypy strict, ruff, pydoclint, SHA pinning, least-privilege CI) and structure gates do not exist (12 import cycles, 249 lazy imports, 351 duplicated windows in tool definitions, 91 functions with 8+ parameters, integration suite outside the required gate, coverage informational, required lint check passes with no verdict). The plan makes structure mechanical first, then burns the debt down under those gates.

## Owner decisions (2026-09-04, binding)

- Required lint check goes **fail-closed** on no-verdict (#2296); #1653's absorb direction is closed.
- Docstring enforcement (`D`/`DOC`) stays **in full** everywhere. No docstring pruning in this roadmap.
- Stale new-tool PRs (#1156, #1157, #1158, #1159, #1160, #1162, #1163, #1529, #1276, #1278) are **parked** (draft + `blocked` label) until #2311 acceptance criteria hold. #1486, #1268, #2150 are **rebase-or-redo** steps in the tracks below.
- Structural gates ship as **lintro tool plugins** (#2289, #2292), not CI-only steps.
- Release cadence stays 1 merged PR = 1 release PR per repo convention.

## Phase 0 — Gates (#2287) — serial, in this order

| # | Issue | Done when | Do not touch |
| --- | --- | --- | --- |
| 0.1 | #2289 | `lintro list-tools` shows import-linter | contracts, `lintro/ai` |
| 0.2 | #2290 | contracts green with baseline; guard test at 11 cycles | any cycle except `enums→models` |
| 0.3 | #2291 | ruff structural families on; baseline test | function bodies |
| 0.4 | #2292 | `lintro list-tools` shows pylint | definitions |
| 0.5 | #2293 | R0801 baseline recorded and enforced | definitions |
| 0.6 | #2294 | coverage blocking, branch on | tests |
| 0.7 | #2295 | one pytest config, no fail-fast | `--ignore=tests/integration` |
| 0.8 | #465 | integration suite in the required path; tool-missing fails in Docker | gate scripts |
| 0.9 | #2296 | no-verdict → red | lint scope / retry selection |
| 0.10 | #2297 | dead wiring gone; one fallback image pin | gate scripts |

**Checkpoint (owner review, the only one in the plan):** after 0.10, confirm the baselines are honest (numbers pasted in each PR match `main`) and that a deliberately bad PR fails each gate. Then Phase 1 may start.

## Phase 1 — two tracks, may run in parallel by separate agents

The tracks touch disjoint packages. **Core track never edits `lintro/ai/**`; AI track never edits anything outside `lintro/ai/**`, `lintro/mcp/**`, `lintro/cli_utils/commands/review.py`, and their tests.** A change that needs the other track's package is filed as an issue on that track, not made.

### Core track (serial)

| # | Issue | Blocked by | Done when |
| --- | --- | --- | --- |
| C.1 | #1739 (delete `setup`, health score) | 0.10 | files gone, docs updated |
| C.2 | #1305 (lazy-import cold start; rebase PR #1486 or redo) | C.1 | `python -X importtime -c "import lintro.cli"` < 200 ms; `lintro --version` imports nothing from `lintro.ai`; #2290 forbidden-contract `ignore_imports` for the config chain deleted |
| C.3 | #2311 (factor tool definitions) | C.2 | #2293 baseline 0; `type: ignore` in definitions ≤ 2; package-per-tool |
| C.4 | #1740 → #1741 → #1742 → #1743 → #1744 → #1745 → #1746 → #1747 → #1748 (the #1735 claims/ordering epic, steps 2–10, in that order) | C.3 | each step's own acceptance criteria; #1747 deletes `utils/unified_config*` |
| C.5 | #2312 (dissolve `utils`) | C.4 | layers contract has no `utils` ignores; cycle count ≤ 3 |
| C.6 | #2313 (option dataclasses) | C.5 | no core function > 8 params or CC > 15 |
| C.7 | #1995 (module-size burn-down, Phases 1–3; Phase 0 re-homed to #2303) | C.6 | `[tool.lintro.module_size]` baseline empty at threshold 600; tests under the gate |
| C.8 | #1225 (packaging; rebase PR #1268 or redo; add MANIFEST/sdist scope) | any time after 0.10 | `packages.find`, `py.typed`, sdist without tests |
| C.9 | #1230, #2002 (small core audits) | C.5 | their own criteria |
| C.10 | #2314, #2315 (deps, unit-test hygiene) | 0.10 | their own criteria |

### AI track (serial)

| # | Issue | Blocked by | Done when |
| --- | --- | --- | --- |
| A.1 | #2298 | 0.10 | gap table on #1972; goldens; ADR |
| A.2 | #2299 | A.1 | one resolver; `apply_transport_override` gone |
| A.3 | #2300 | A.2 | `review_command` < 150 lines; parity on `PreparedReview` |
| A.4 | #2301 (5 PRs) | A.3 | orchestrator out of size baseline; no module > 500 |
| A.5 | #2302 | A.4 | `aclose` only in session; #1972 closable |
| A.6 | #2303 → #2304 → #2305 | A.5 | #1974 closable; no v1 paths |
| A.7 | #1996, #1973, #1998, #1871 (small AI refactors) | A.6 | their own criteria |
| A.8 | #2306 → #2307 → #2308 → #2309 → #2310 | A.7 | #1999 closable |
| A.9 | #2143 (provider-agnostic docs; rebase PR #2150 or redo; code default already on `main`) | A.8 | docs equal-footing |

## Phase 2 — un-park

When C.3 holds: comment on each parked tool PR with the new definition shape; the agent rebases one at a time onto the package-per-tool layout, or closes and re-implements from the issue if the rebase is larger than the original diff.

## Phase 3 — ratchet to zero

Repeat until every baseline is empty: `[tool.importlinter] ignore_imports`, `[tool.ruff.lint.per-file-ignores]` structural block, `[tool.lintro.pylint] duplicate_code_baseline`, `[tool.lintro.module_size] baseline`. Then delete the baseline machinery and the guard constants. Close #2287 and this roadmap.

## Execution protocol (binding for the executing agent)

1. Work the tables top to bottom. Never start a row whose "Blocked by" is not merged to `main` and released.
2. One branch and one PR per issue (or per PR listed inside an issue). PR body: `Part of #2288`, `Closes #<issue>`. Title = issue title subject.
3. Before every commit: `uv run lintro fmt`, `uv run lintro chk`, `uv run pytest --maxfail=0` on touched packages. Before every PR: full unit suite.
4. A PR may only **shrink** a gate baseline. If a change needs a baseline to grow, stop, file an issue describing why, and pick the next row.
5. Behaviour-preserving refactors keep goldens byte-identical. If a golden must change, the PR description says which and why, and the owner approves before merge.
6. Line numbers in issues were captured on `main @ 0c5453ce` (2026-09-04) and drift. Trust paths and function names.
7. Every issue closed gets a comment linking the merging PR and release. Every issue found stale during execution gets a comment saying what changed, not a silent edit.
8. Stop conditions: a required check red for a reason outside the current issue's files; a golden diff; a needed baseline increase; a conflict with the other track's package. On any of these, comment on this roadmap and move to the next unblocked row.
9. Never weaken a gate to get through a red.

## Out of scope for this roadmap

New tools (parked), new AI features (#2284, #2269, #2265, #2099, #2147 wait), the site (#1917 phases), display redesign (#779), performance epics (#597), SARIF parser research (#1066), conventions plugin (#1246, revisit after C.3 as a natural home for repo-specific rules).

## References

- Audit report 2026-09-03 (sections Architecture, Code quality, Tests, CI/CD, Dependencies, Scorecard, Fix list).
- #2287, #1972, #1974, #1999, #1735, #1995, #2245.

**Comment by TurboCoder13** [comment]
### Row 0.2 (#2290) — stop-condition note: `dogfooding-lint` is red on `main`

Per execution protocol #8 ("a required check red for a reason outside the current issue's files"), reporting rather than fixing.

`dogfooding-lint / 🛠️ Dogfooding Lint` fails at step **Run lintro quality checks** on `main` itself:

| Branch | Run | Failing step | Duration |
| --- | --- | --- | --- |
| `main` @ `7f5debc0` | [33953920786](https://github.com/lgtm-hq/py-lintro/actions/runs/33953920786) | Run lintro quality checks | 11m24s → failure |
| #2333 @ `8c0e8729` | [33955119079](https://github.com/lgtm-hq/py-lintro/actions/runs/33955119079) | Run lintro quality checks | 19m17s / 19m24s / 17m41s → failure (3 attempts + retries) |

`main` carries no `[tool.importlinter]` contracts, so #2333's config is not the cause. Every other required check on #2333 is green (34 pass), and `uv run lintro chk` is clean locally on that branch (0 issues, 100/100), including `--tools import-linter`.

Row 0.2's own acceptance criteria are met; this gate needs its own fix before the Phase 0 checkpoint.

**Comment by TurboCoder13** [comment]
Execution note (2026-09-05, ~13:00 UTC): runner-shutdown wave on GitHub-hosted runners. Since ~10:00 UTC every `dogfooding-lint` job (primary and retry) on #2323, #2334, #2326 and on `main` has died with "The runner has received a shutdown signal" (exit 143) after 12-19 minutes; before that the same jobs passed at 15-19 minutes. AI Review jobs die the same way. No code change is involved (main's own dogfood dies identically, and the logs stop at "Processing files" before any tool reports). Handling: manual reruns of the failed jobs (auto-rerun budget exhausted), stale pending `main` runs for superseded commits cancelled to unclog the `docker-ci-refs/heads/main` queue. Phase 0 progress: #2289 merged+released, #2290 merged; #2291 (#2323) is green except this job. A separate CI-efficiency investigation is being started by the owner; the blocked `hosted-compute-watchdog-prod-*.githubapp.com` egress seen in harden-runner logs is a lead for it.

**Comment by TurboCoder13** [comment]
Decision needed / taken (2026-09-05): the #2290 `layers` baseline froze the `tools.definitions.* -> lintro.plugins.{base,protocol,registry}` edges under #2311 before #2292's pylint definition existed. Every definition has those three edges by construction, and the ratchet rule read literally would block rows 0.4/0.5 (and every future tool) behind C.3 (#2311). Resolution applied on PR #2334: the three pylint edges are recorded under the same #2311 owner (141 → 144), with an explicit one-sentence exception in the pyproject ratchet comment and AGENTS.md: a new tool definition under the current pattern records its three plugin-layer edges under #2311, which deletes them all when it factors the pattern. Owner veto welcome; otherwise this is the standing rule until #2311 lands.

**Comment by TurboCoder13** [comment]
## Phase 0 checkpoint verification (2026-09-06)

Local verification of the Phase 0 owner checkpoint. Ran in a detached worktree at `main @ 16da987e` ("chore(ci): pin the fork-fallback image once and delete orphaned scripts (#2322)"), which is `origin/main` head, after `uv sync --dev --extra full`. No PR opened, nothing pushed, nothing committed; the tree was restored to clean after every deliberate break.

**Verdict: Phase 0 passes. All ten gates are honest on `main`, and every one of the eight deliberate breaks goes red.** Three discrepancies, none of them a hole in a gate — see the bottom.

### Part A — baselines are honest on `main`

| # | Gate | Expected | Measured | Verdict |
| --- | --- | --- | --- | --- |
| A1a | `uv run lintro chk . --tools import-linter` | green | PASS, 0 issues | ✅ |
| A1b | `core-does-not-import-ai` `ignore_imports` | 15 | 15 (`unmatched_ignore_imports_alerting = error`) | ✅ |
| A1c | `layers` `ignore_imports` | 232 (229 + 3 pylint, #2333/#2334) | 232 (`unmatched_ignore_imports_alerting = error`) | ✅ |
| A1d | `scripts/ci/import_matrix.py` two-way cycles | 11 (`EXPECTED_CYCLES` in `tests/unit/test_import_boundaries.py`) | 11 | ✅ |
| A2a | structural baseline files | 100 max, minus the `fix-markdown-docs` entry #2322 removed | 99 in `pyproject.toml`, 99 in the test's `BASELINE` mapping | ✅ (see D1) |
| A2b | structural baseline (file, rule) pairs | 201 max, same minus one | 200 in `pyproject.toml`, 200 in `BASELINE` | ✅ (see D1) |
| A2c | RUF100 clean | 0 | 0 under the project config (`uv run ruff check .` → "All checks passed!"; `RUF100` is in `select`) | ✅ (see D2) |
| A3 | pylint `R0801` on `lintro/tools/definitions/*.py` | 34 = `duplicate_code_baseline` | 34 messages, all `R0801` | ✅ |
| A4 | unit-suite coverage vs `fail_under = 81` | ~83% | **83.35%**, "Required test coverage of 81.0% reached"; 10000 passed, 87 skipped | ✅ |
| A5a | exactly one pytest config source | `configfile: pyproject.toml`, no `pytest.ini` | `configfile: pyproject.toml`, `testpaths: tests`; no `pytest.ini`, no `setup.cfg`; `tox.ini` exists but has no pytest section | ✅ |
| A5b | no `--maxfail` in config | absent | absent — only the explanatory comment at `pyproject.toml:1009` ("No --maxfail here on purpose (issue #2295)") | ✅ |
| A5c | `-x` in `.github/workflows/test-ci.yml` | absent | absent (no `-x`, no `maxfail`) | ✅ |
| A6a | `changes` job in `test-ci.yml` | gone | gone | ✅ |
| A6b | `rg '0\.137\.0@sha256' .github` | empty | empty (exit 1) | ✅ |
| A6c | fork-fallback image pinned once | one site | one: `docker-ci.yml:87` `LINTRO_FORK_FALLBACK_IMAGE: ghcr.io/lgtm-hq/py-lintro:0.147.0@sha256:b5624b8…`, consumed by four references | ✅ |
| A7a | `tests/integration` uses only `require_tool`/`require_command` | no raw skips | `_tools.py` (the helper) plus **two modules with raw `pytest.mark.skipif`** | ⚠️ D3 |
| A7b | `LINTRO_TOOLS_IMAGE=1` set in both places | set | `docker-compose.yml:60`, `docker/tools.Dockerfile:39` | ✅ |
| A8 | `assert-required-check.sh` fails closed | script tests green | `uv run pytest tests/scripts/test_code_quality_gate_scripts.py -q` → **75 passed** | ✅ |

### Part B — a deliberately bad change fails each gate

Each change was made, the gate run, the message recorded, then `git checkout -- .`. The tree was verified clean (`git status --porcelain` empty, `git clean -nd` empty) after the last one.

| # | Bad change | Gate | Result | Failure message |
| --- | --- | --- | --- | --- |
| B1 | `import lintro.cli_utils` in `lintro/enums/tool_name.py` | `lintro chk . --tools import-linter` | ❌ FAIL, 1 issue | `layers` / ERROR / `lintro.enums.tool_name -> lintro.cli_utils` |
| B2 | CC-16 function in `lintro/enums/__init__.py` | `lintro chk . --tools ruff` | ❌ FAIL | `C901` — ``` `_bad_complexity` is too complex (16 > 15) ``` |
| B3 | 9-parameter function, same file | `lintro chk . --tools ruff` | ❌ FAIL | `PLR0913` — `Too many arguments in function definition (9 > 8)` |
| B4 | 55-line method copied verbatim from `yamllint.py` into `black.py` | `lintro chk lintro/tools/definitions --tools pylint` | ❌ FAIL, 1 issue | `duplicate-code count 35 exceeds baseline 34; baseline may only shrink` |
| B5 | `fail_under = 99` | `pytest tests/unit/tools/pytest -q --cov` | ❌ exit 1 (148 tests passed) | `FAIL Required test coverage of 99.0% not reached. Total coverage: 11.22%` |
| B6 | one entry added to the structural baseline block | `pytest tests/unit/test_ruff_baseline.py -q` | ❌ 1 failed, 4 passed | `AssertionError: [structural baseline may only shrink: delete per-file-ignores entries for C901/PLR0912/PLR0913/PLR0915, never add them] Expected <['lintro/enums/__init__.py:C901']> to be empty, but was not.` |
| B7 | one `ignore_imports` line added to the `layers` contract | `lintro chk . --tools import-linter` | ❌ FAIL (tool execution failed) | `lint-imports`: `No matches for ignored import lintro.enums.tool_name -> lintro.cli_utils.` — see D4 |
| B8 | `duplicate_code_baseline = 35` | `pytest tests/unit/test_duplicate_code_baseline.py -q` | ❌ 2 failed, 2 passed | `Expected <35> to be less than or equal to <34>, but was not.` and `Expected <34> to be equal to <35>, but was not.` |

Every gate is enforcing, not decorative. B1–B4 fail through `lintro` itself (the gates are tool plugins as #2289/#2292 intended), B5–B8 through the ratchet tests.

### Discrepancies

**D1 — the structural baseline ceilings are one entry stale (cosmetic).** `pyproject.toml` and `BASELINE` in `tests/unit/test_ruff_baseline.py` both hold 99 files / 200 pairs after #2322 removed the `fix-markdown-docs` entry, but `BASELINE_MAX_FILES = 100` and `BASELINE_MAX_SUPPRESSIONS = 201` were not lowered with it. This is **not** a hole: the identity check (`test_structural_baseline_matches_pyproject_exactly`) fails on any added entry regardless of the ceilings — B6 proves it. Still, the ratchet rule says the numbers only shrink, so the constants should be dropped to 99/200 in the next PR that touches the file.

**D2 — the checkpoint's own RUF100 command is misleading, the gate is fine.** `uv run ruff check --select RUF100 .` reports 36 errors, all of the form "Unused `noqa` directive (non-enabled: `E402`/`F401`/`B904`/`F822`/`N817`)". That is a ruff artifact: `--select RUF100` disables every other rule, so every legitimate `# noqa` for a now-unselected rule reads as dead. The real gate is `uv run ruff check .` under the project config, where `RUF100` is in `select` — that reports **All checks passed!**. The command in the checkpoint text should be corrected; the baseline is honest.

**D3 — two integration modules bypass `require_tool`, weakening #465 for the two newest gates.** `tests/integration/tools/import_linter/test_check.py:19` and `tests/integration/tools/pylint/test_check.py:18` use a raw `pytestmark = pytest.mark.skipif(shutil.which(...) is None, ...)` rather than `require_tool`/`require_command`/`gate` from `tests/integration/_tools.py`. Consequence: inside the tools image (`LINTRO_TOOLS_IMAGE=1`) a missing or broken `lint-imports`/`pylint` **skips silently** instead of raising `MissingToolError` — exactly the image regression #465 exists to catch. The two modules were added by #2289 and #2292, the gate-plugin PRs, and appear to predate or miss the `_tools.py` convention. Fix is one line each: replace the `skipif` with the `_tools.py` helper. This is the only finding that touches gate strength, and it affects the integration suite only — the unit ratchets and the `lintro chk` paths are unaffected.

**D4 — an unmatched `ignore_imports` goes red without saying why.** B7 fails correctly, but `lintro chk . --tools import-linter` renders only `✗ Tool execution failed` / `FAIL ERROR` with `Total Issues 0`; the actual reason ("No matches for ignored import …") is visible only by running `uv run lint-imports --config pyproject.toml` directly. The gate holds, but an agent hitting this in CI gets no actionable message. Worth a follow-up issue on the import-linter plugin's error surfacing.

### Recommendation

Phase 0 is verifiable and honest; **Phase 1 may start.** D3 should be filed and fixed (one line per file, no baseline movement); D1 and D4 are follow-ups that block nothing.

**Comment by TurboCoder13** [comment]
## AI track A.1 (#2298) — delivered, blocked on a red required check outside its files

PR #2363 is open (`Closes #2298`, `Part of #1972`, `Part of #2288`). The gap table is posted on #1972.

**Stop condition 8 hit:** `test-compat / Python Compatibility` (a required check) is red on the **Python 3.11** matrix entry for `tests/unit/test_duplicate_code_baseline.py::test_baseline_matches_what_pylint_reports` — `Expected <33> to be equal to <34>`. The 3.14 entry passes, and the same test passes on a clean `origin/main` worktree under Python 3.11 locally. PR #2363 changes no file under `lintro/` and does not touch `pyproject.toml`, so the baseline drift is environmental, not diff-caused.

Fixing it means editing `pyproject.toml` / a core guard test, which the AI track may not do. Filed as **#2365** on the core track with the evidence and three candidate fixes.

Also red, both in the `lgtm-ci` reusable comment publishers rather than in the repo: `dogfooding-pr-comment / 🛠️ Dogfooding Lint PR Comment` and `test-coverage / publish-test-summary / Publish test summary` — each failed only on its "Publish … summary" step while every earlier step succeeded. Neither is a required check. `test-suite-coverage / 🧪 Test Suite & Coverage` is red as a mirror of the compat failure, not independently.

Everything else on #2363 is green: `lintro-code-quality / 🛠️ Lintro Code Quality`, CodeQL, security audit, Docker integration, coverage on 3.12.

**Comment by TurboCoder13** [comment]
Execution note: main's dogfood on 9f702190 (#2376, PR A of #2311) is red on commitlint header-max-length (squash subject 104 chars: long title + "— PR A" + "(#2376)"). Message hygiene only, self-heals on the next merge; no history rewrite. Rule for the remaining #2311 PRs: titles ≤ 80 chars.

**Comment by TurboCoder13** [comment]
Baseline note (PR B, #2380 → 06bb54ce): `lintro/tools/core/fix_runner.py` is the location #2311 mandates, and `tools` / `plugins` are siblings in the `layers` contract, so two `ignore_imports` edges (`fix_runner -> lintro.plugins.{base,file_processor}`) were recorded under the #2311-owned block (144 → 146), same treatment as the tool-definition edges already recorded there. Net for the merge: duplicate-code baseline 34 → 29, no other baseline grew. PRs G–K retire the block.

**Comment by TurboCoder13** [comment]
A.4 (#2301) complete via #2383, #2384, #2388, #2394, #2398, #2401 (final squash 6e2ed12b). Orchestrator 3014 → 150 lines; module_size baseline now only doctor.py; ruff structural baseline 94/182 → 90/175; per-module (≤500 lines) and per-function (≤8 params) ratchets added for lintro/ai/review. Deferred to C.7 #1995: chunker/ and context/ subpackages over 500 lines. Next AI step: A.5 #2302.

**Comment by TurboCoder13** [comment]
C.3 (#2311) status: PRs G–K are all open (#2397 merged; #2402 merged; #2406 PR I, #2408 PR J, #2409 PR K stacked and green except the Cursor-gated AI Review). Decision recorded on #2311: the C.3 row criteria are met by PR K; issue-level ACs on tool-name mentions and definition size move to C.5/C.9 and C.7. The 144 tools→plugins ignore_imports are real base-class edges behind a plugins/tools cycle (discovery lives in lintro/plugins), now owned by #2410 for the Phase 3 ratchet. Merge queue is blocked on the Cursor account usage limit (AI Review job) — owner action needed.

**Comment by TurboCoder13** [comment]
Merge-gate decision (03:xx): the CI 'AI Review' job is red on every PR because the Cursor account is out of usage (ActionRequiredError: out of usage). Per the workflow's own documented policy (ai-review.yml NO-SILENT-SKIP note: intentionally NOT a required check; a billing/quota condition is loud but never blocks a merge) and the owner's rule that lintro AI reviews are advisory, PRs whose every other check is green and whose review threads are all resolved are being merged in queue order. AI Review will be rerun on affected heads once the Cursor quota resets; findings, if any, will be addressed in follow-ups.

**Comment by TurboCoder13** [comment]
C.3 (#2311) complete via PR K #2409 (squash e0f3786c): package-per-tool layout, definitions/ shims deleted, discovery scans per-tool packages, duplicate-code gate zero-tolerance, type: ignore in definitions = 1. Follow-ups: #2410 (144 tools→plugins edges), #2400 (pre-existing defects in relocated files), tool-name mentions → C.5/C.9, definition size → C.7. Phase 2 (un-park tool PRs) can begin; C.4 #1740/#1741 are stacked and in flight.

**Comment by TurboCoder13** [comment]
New child epic attached: #2634 (release supply-chain hardening), 11 cross-repo sub-issues across py-lintro, lgtm-ci and homebrew-tap. Placement: Tier 4 of the standing queue, after the in-flight #2607, #2604 and #2603 and ahead of milestone 0 phase 1. Owner decisions of 2026-09-13 are recorded in the epic body. Unblocked immediately: #2630, #2631, lgtm-hq/lgtm-ci#962.
